//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonareSange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorPersonalDetail
    {
        public int PersonalDetailsId { get; set; }
        public string email { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string DonorId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> DonorCNP { get; set; }
        public string sex { get; set; }
        public Nullable<int> addressRegistred { get; set; }
        public Nullable<int> addressCurrent { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
