//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonareSange.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PersonalDetailsStaffMember
    {
        [Key]
        public int PersonalDetailsId { get; set; }
        public string email { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string StaffId { get; set; }
        public Nullable<int> CentreId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Centre Centre { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
